// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using deLuca.InventoryManager.Api.Data;

#nullable disable

namespace deLuca.InventoryManager.Api.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("deLuca.InventoryManager.Api.Data.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Nome = "Cabos e Conectividade",
                            Prefixo = "CAB-"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Nome = "Periféricos",
                            Prefixo = "PER-"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Nome = "Equipamentos / Dispositivos",
                            Prefixo = "EQP-"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Nome = "Hardware / Componentes Internos",
                            Prefixo = "HDW-"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Nome = "Armazenamento de Dados",
                            Prefixo = "ARM-"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Nome = "Ferramentas e Insumos",
                            Prefixo = "FER-"
                        });
                });

            modelBuilder.Entity("deLuca.InventoryManager.Api.Data.ItemTecnologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoFormatado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubcategoriaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("deLuca.InventoryManager.Api.Data.Subcategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Subcategorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CategoriaId = 1,
                            Nome = "Vídeo"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CategoriaId = 1,
                            Nome = "Dados"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CategoriaId = 1,
                            Nome = "Rede"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CategoriaId = 1,
                            Nome = "Áudio"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CategoriaId = 1,
                            Nome = "Energia"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CategoriaId = 2,
                            Nome = "Apontamento & Digitação"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CategoriaId = 2,
                            Nome = "Áudio Visual"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CategoriaId = 2,
                            Nome = "Exibição"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CategoriaId = 2,
                            Nome = "Impressão"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CategoriaId = 3,
                            Nome = "Computação Pessoal"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            CategoriaId = 3,
                            Nome = "Infraestrutura de Rede"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            CategoriaId = 3,
                            Nome = "Energia"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            CategoriaId = 4,
                            Nome = "Processamento"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            CategoriaId = 4,
                            Nome = "Memória"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            CategoriaId = 4,
                            Nome = "Placas"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            CategoriaId = 4,
                            Nome = "Energia Interna"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            CategoriaId = 4,
                            Nome = "Refrigeração"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            CategoriaId = 5,
                            Nome = "Interno"
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            CategoriaId = 5,
                            Nome = "Externo"
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            CategoriaId = 5,
                            Nome = "Portátil/Flash"
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            CategoriaId = 6,
                            Nome = "Ferramentas Manuais"
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            CategoriaId = 6,
                            Nome = "Diagnóstico"
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            CategoriaId = 6,
                            Nome = "Insumos (Consumíveis)"
                        });
                });

            modelBuilder.Entity("deLuca.InventoryManager.Api.Data.ItemTecnologia", b =>
                {
                    b.HasOne("deLuca.InventoryManager.Api.Data.Subcategoria", "Subcategoria")
                        .WithMany("Itens")
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("deLuca.InventoryManager.Api.Data.Subcategoria", b =>
                {
                    b.HasOne("deLuca.InventoryManager.Api.Data.Categoria", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("deLuca.InventoryManager.Api.Data.Categoria", b =>
                {
                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("deLuca.InventoryManager.Api.Data.Subcategoria", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
